# .github/workflows/ci.yml
name: CI Hello World
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, CI!"

  hello2:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, CI! nochmals"